### ISSUE TITLE
Application not starting.

### ISSUE THREAD

**Issue by kajlando** [kajlando/wine-tkg-fl-studio-20.8-patch#1]

**Comment by mattjschmidt** [comment]
Hi! I'm on Ubuntu 20.04 and I followed your steps of extracting fl-wine-tkg-staging-fsync-git-6.4.r0.g7ec998e1-322-x86_64.7z to ~/.local/share/lutris/runners/wine, configuring Lutris to use that instance of wine however I'm running into issues. The installer fails to boot at all with no message.

I feel like I must be missing something. What are the exact steps to using your patch with Lutris?

Thank you for this!

**Comment by kajlando** [comment]
Unfortunately 20.04 has glibc version 2.31 which won't work with this package because it was build on 2.33.
There are three solutions:
- wait for a patch in Wine itself,
- run 20.7.3,
- or try to compile patched Wine yourself.

**Comment by mattjschmidt** [comment]
Very nice! Thanks!

**Comment by kajlando** [comment]
> Very nice! Thanks!
https://github.com/kajlando/wine-tkg-fl-studio-20.8-patch/releases/tag/6.4.r5.gf8b6fde4

**Comment by mattjschmidt** [comment]
You are amazing! Booted right up. Thanks again!

**Comment by kajlando** [comment]
I'm glad I could help :)
