### ISSUE TITLE
Does not work in Gentoo Linux

### ISSUE THREAD

**Issue by bplx** [kajlando/wine-tkg-fl-studio-20.8-patch#2]
Steps i did: 

1. Went into the wine-tkg-git folder
2. Ran ./non-makepkg-build.sh

Nothing happened
I may sound dumb but that's because i am, i have absolutely no idea what to do!

**Comment by kajlando** [comment]
I guess by "Nothing happened" I understand that there was no output or anything.
Try makepkg -si

**Comment by bplx** [comment]
but i use gentoo..?

**Comment by bplx** [comment]
oh
also, what i mean by nothing happened meaning it semeed to properly install but fl studio doesn't work

**Comment by bplx** [comment]
prepare.log: https://dpaste.com/G2CEY93LJ
last_build_config.log: https://dpaste.com/4TF83XV63

**Comment by kajlando** [comment]
Unfortunately I won't be able to help you.
You could read:
https://github.com/Frogging-Family/wine-tkg-git/blob/f98b98bf10f36dd906f1c986309b0a19c20ac8bc/wine-tkg-git/README.md
Use prebuild package with Lutris.
Or report an issue to Tk-Glitch. They should be able to help.
https://github.com/Frogging-Family/wine-tkg-git/issues

**Comment by kajlando** [comment]
I'm sorry unfortunately I won't be able to help you.
You could read:
https://github.com/Frogging-Family/wine-tkg-git/blob/f98b98bf10f36dd906f1c986309b0a19c20ac8bc/wine-tkg-git/README.md
Use prebuild package with Lutris.
Or report an issue to Tk-Glitch. They should be able to help.
https://github.com/Frogging-Family/wine-tkg-git/issues

**Comment by kajlando** [comment]
Have you tried running it with Lutris?

**Comment by kajlando** [comment]
As Tk-Glitch wrote non-makepkg doesn't apply Wine system wide.
**First solution:**

wine-tkg-git-master/wine-tkg-git/pkg/wine-tkg-staging-fsync-git
copy all from usr to one folder  then move it to ~/.local/share/lutris/runners/wine and run FLS with patched Wine inside Lutris or any other launcher.

**Second solution:**
wine-tkg-git-master/wine-tkg-git/pkg/wine-tkg-staging-fsync-git
copy all from /usr/bin to /bin

**Comment by kajlando** [comment]
Your build should appear in wine-tkg-git-master/wine-tkg-git/pkg because ./non-makepkg-build.sh doesn't apply Wine system wide.

**Comment by kajlando** [comment]
Your build should be in wine-tkg-git-master/wine-tkg-git/pkg because ./non-makepkg-build.sh doesn't apply Wine system wide.

**Comment by kajlando** [comment]
Your build should be in wine-tkg-git-master/wine-tkg-git/pkg because ./non-makepkg-build.sh doesn't apply Wine system wide.
